services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    command: --quiet
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    depends_on:
      - server

volumes:
  mongo_data: